// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllore;

import onegame.modello.tabelle.Utente;

/************************************************************/
/**
 * 
 */
public class SessionManager {
	/**
	 * 
	 */
	private Utente currentUser;

	/**
	 * 
	 */
	public void login() {
	}

	/**
	 * 
	 */
	public void logout() {
	}

	/**
	 * 
	 */
	public void isGuest() {
	}

	/**
	 * 
	 */
	public void getUser() {
	}
}
