// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllore;

import vista.TutorialView;

/************************************************************/
/**
 * 
 */
public class TutorialController {
	/**
	 * 
	 */
	private TutorialView tutorialView;

	/**
	 * 
	 */
	public void mostraTutorial() {
	}

	/**
	 * 
	 */
	public void navigaTutorial() {
	}

	/**
	 * 
	 */
	public void chiudiTutorial() {
	}
}
