// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllore;

import modello.Partita;
//import server.NetworkService;
import vista.GameView;

/************************************************************/
/**
 * 
 */
public class GameController {
	/**
	 * 
	 */
	private GameView gameView;
	/**
	 * 
	 */
	private Partita partita;
	/**
	 * 
	 */
	//private NetworkService networkService;
	/**
	 * 
	 */
	private SessionManager sessionManager;

	/**
	 * 
	 */
	public void giocaCarta() {
	}

	/**
	 * 
	 */
	public void pescaCarta() {
	}

	/**
	 * 
	 */
	public void chiamaUno() {
	}

	/**
	 * 
	 */
	public void gestisciFineTurno() {
	}

	/**
	 * 
	 */
	public void gestisciFinePartita() {
	}

	/**
	 * 
	 */
	public void abbandonaGioco() {
	}
}
