// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllore;

import vista.HomeView;

/************************************************************/
/**
 * 
 */
public class HomeController {
	/**
	 * 
	 */
	private HomeView homeView;
	/**
	 * 
	 */
	private SessionManager sessionManager;

	/**
	 * 
	 */
	public void giocaVsComputer() {
	}

	/**
	 * 
	 */
	public void giocaVsAmici() {
	}

	/**
	 * 
	 */
	public void mostraRegolamento() {
	}

	/**
	 * 
	 */
	public void esci() {
	}
}
