// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllore;

//import server.StatsService;
import vista.StatsView;

/************************************************************/
/**
 * 
 */
public class StatsController {
	/**
	 * 
	 */
	private StatsView statsView;
	/**
	 * 
	 */
	//private StatsService statsService;
	/**
	 * 
	 */
	private SessionManager sessionManager;

	/**
	 * 
	 */
	public void mostraStatistiche() {
	}

	/**
	 * 
	 */
	public void aggiornaStatistiche() {
	}
}
