// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package onegame.client.controllore;

import onegame.client.vista.LobbyView;

/************************************************************/
/**
 * 
 */
public class LobbyController {
	/**
	 * 
	 */
	private LobbyView lobbyView;
	/**
	 * 
	 */
	private SessionManager sessionManager;
	/**
	 * 
	 */
	//private undef lobbyService;

	/**
	 * 
	 */
	public void creaLobby() {
	}

	/**
	 * 
	 */
	public void entraLobby() {
	}

	/**
	 * 
	 */
	public void avviaPartita() {
	}

	/**
	 * 
	 */
	public void abbandondaLobby() {
	}
}
