// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package onegame.client.controllore;

import onegame.client.vista.LoginView;

/************************************************************/
/**
 * 
 */
public class LoginController {
	/**
	 * 
	 */
	private LoginView loginView;
	/**
	 * 
	 */
	//private AuthService authService;
	/**
	 * 
	 */
	private SessionManager sessionManager;

	/**
	 * 
	 */
	public void gestisciLogin() {
	}

	/**
	 * 
	 */
	public void gestisciRegistratione() {
	}

	/**
	 * 
	 */
	public void gestisciAccessoAnonimo() {
	}

	/**
	 * 
	 */
	public void mostraError() {
	}
}
