// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package onegame.client.controllore;

import onegame.client.vista.StatsView;

/************************************************************/
/**
 * 
 */
public class StatsController {
	/**
	 * 
	 */
	private StatsView statsView;
	/**
	 * 
	 */
	//private StatsService statsService;
	/**
	 * 
	 */
	private SessionManager sessionManager;

	/**
	 * 
	 */
	public void mostraStatistiche() {
	}

	/**
	 * 
	 */
	public void aggiornaStatistiche() {
	}
}
