// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.tabelle;

/************************************************************/
/**
 * 
 */
public class Utente {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public String username;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public int vittorie;

	/**
	 * 
	 */
	public void getId() {
	}

	/**
	 * 
	 */
	public void getUsername() {
	}

	/**
	 * 
	 */
	public void getVittorie() {
	}

	/**
	 * 
	 */
	public void incrementaVittorie() {
	}
}
