// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package vista;

/************************************************************/
/**
 * 
 */
public class GameView {
	/**
	 * 
	 */
	//public undef labelTurno;
	/**
	 * 
	 */
	//public undef pescaButton;
	/**
	 * 
	 */
	//public undef carte;

	/**
	 * 
	 */
	public void updateHand() {
	}

	/**
	 * 
	 */
	public void showError() {
	}
}
