// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package vista;

/************************************************************/
/**
 * 
 */
public class LoginView {
	/**
	 * 
	 */
	//public undef passwordField;
	/**
	 * 
	 */
	//public undef loginButton;
	/**
	 * 
	 */
	//public undef registerButton;
	/**
	 * 
	 */
	//public undef playAsAnonymousButton;
	/**
	 * 
	 */
	//public undef usernameField;

	/**
	 * 
	 */
	public void addLoginListener() {
	}

	/**
	 * 
	 */
	public void addRegisterListener() {
	}

	/**
	 * 
	 */
	public void addAnonymousPlayer() {
	}
}
