// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package onegame.modello;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Stack;

import com.fasterxml.jackson.annotation.JsonIgnore;

import onegame.modello.carte.*;

/************************************************************/

/**
 * classe Mazzo (unicamente associato ad una partita)
 * 
 * attributi importanti:
 * una lista di carte (lette da file)
 * riferimento alla pilaScarti della partita (per ricostruzione diretta, senza passare per la partita)
 * 
 * metodi importanti:
 * mescola()--> mescola le carte del mazzo
 * pesca()--> pesca una carta, togliendola dal mazzo; se non ci sono più carte nel mazzo invoca prima ricostruisciMazzo() 
 * pescaN()--> pesca N carte (intero passato ad input), richiamando pesca() N volte
 * creaMazzo()--> crea un mazzo leggendo da file "mazzo" le carte
 * ricostruisciMazzo()--> ricrea mazzo a partire dalla pilaScarti associata
 * 
 */
public class Mazzo {
	private Stack<Carta> carte;
	@JsonIgnore
	private PilaScarti pila;

	//costruttore vuoto per Jackson
	public Mazzo() {
		this.carte = new Stack<>();
	}
	
	/**
	 * metodo di inizializzazione del mazzo 
	 * (da invocare solo in costruttore Partita non vuotot)
	 */
	public void inizializzaNuovoMazzo() {
		this.carte.clear();
		init();
	}
	
	public Stack<Carta> getCarte() {
		return carte;
	}

	public void setCarte(Stack<Carta> carte) {
		this.carte = carte;
	}

	@JsonIgnore
	public PilaScarti getPila() {
		return pila;
	}
	
	@JsonIgnore
	public void setPila(PilaScarti pila) {
		this.pila = pila;
	}
	
	@JsonIgnore
	public int getNumeroCarte() {
		return carte.size();
	}
	
	public void mescola() {
		Collections.shuffle(carte);
	}
	
	/**
	 * metodo che legge le carte che ci devono essere in un mazzo, le crea
	 * e le inserisce dentro il mazzo stesso, mescolandolo alla fine
	 * 
	 * @throws IOException errore lettura file
	 */
	@Deprecated
	private void creaMazzoDaFile() throws IOException {
	    try (InputStream is = getClass().getResourceAsStream("/mazzo");
	    	     BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
	        String line;
	        while ((line = br.readLine()) != null) {
	            String[] parts = line.split(",");
	            String tipo = parts[0];
	            Colore colore = Colore.valueOf(parts[1]);
	            int quantita = Integer.parseInt(parts[3]);

	            for (int i = 0; i < quantita; i++) {
	                if (tipo.equals("NUMERO")) {
	                    int numero = Integer.parseInt(parts[2]);
	                    carte.add(new CartaNumero(colore, numero));
	                } else if (tipo.equals("SPECIALE")) {
	                    TipoSpeciale ts = TipoSpeciale.valueOf(parts[2]);
	                    carte.add(new CartaSpeciale(colore, ts));
	                }
	            }
	        }
	    }
	    mescola();
	}
	
	private void init() {
		List<Carta> all = new ArrayList<>();
		for (Colore c : new Colore[] { Colore.ROSSO, Colore.GIALLO, Colore.VERDE, Colore.BLU }) {
			for (int i = 0; i <= 9; i++) {
				all.add(Carta.numero(c, i));
				if (i != 0)
					all.add(Carta.numero(c, i));
			}
			all.add(Carta.skip(c));
			all.add(Carta.skip(c));
			all.add(Carta.cambioGiro(c));
			all.add(Carta.cambioGiro(c));
			all.add(Carta.pescaDue(c));
			all.add(Carta.pescaDue(c));
		}
		for (int i = 0; i < 4; i++)
			all.add(Carta.cambioColore());
		for (int i = 0; i < 4; i++)
			all.add(Carta.pescaQuattro());
		Collections.shuffle(all);
		carte.addAll(all);
	}
	
	/**
	 * metodo che ricostruisce mazzo a partite da pilascarti ad esso associato
	 */
	@JsonIgnore
	public void ricostruisciMazzo() {
		carte.addAll(this.getPila().getScarti());
		this.getPila().getScarti().clear();
		this.mescola();
	}

	public Carta pesca() {
		if (this.isVuoto())
			ricostruisciMazzo();
		if (this.isVuoto()) {
			return null;
		}
		return carte.pop();
	}
	
	public ArrayList<Carta> pescaN(int n) {
		ArrayList<Carta> temp=new ArrayList<>();
		for(int i=0;i<n;i++) {
			temp.add(pesca());
		}
		return temp;
	}

	@JsonIgnore
	public boolean isVuoto() {
		return carte.size() == 0;
	}
	@Override
	public String toString() {
		return "Mazzo [carte=" + carte.size() + "]";
	}
}