// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package onegame.modello;

import java.util.Stack;

import onegame.modello.carte.Carta;

/************************************************************/

/**
 * classe che gestisce la pila degli scarti
 * 
 * attributi importanti:
 * lista di carte=scarti--> la carta sul banco NON appartiene alla pila degli scarti
 * 
 * metodi importanti:
 * mettiCarta()--> aggiunge una carta alla pila degli scarti
 */
class PilaScarti {
	private Stack<Carta> scarti = new Stack<>();
	
	public Stack<Carta> getScarti() {
		return scarti;
	}

	public void setScarti(Stack<Carta> scarti) {
		this.scarti = scarti;
	}

	public PilaScarti() {
		this.scarti=new Stack<>();
	}

	public void mettiCarta(Carta c) {
		scarti.add(c);
	}
	
	@Override
	public String toString() {
		return "Pila [carte=" + scarti.size() + "]";
	}
}
