// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.carte;

import modello.Partita;

/************************************************************/

/**
 * classe che modella una carta numero (estende carta)
 * 
 * attributi importanti:
 * numero
 * 
 * metodi importanti:
 * giocabileSu()--> override da carta (guardare lì per semantica)
 */
public class CartaNumero extends Carta {
	private int numero;

	//costruttore vuoto per Jackson
	public CartaNumero() {this.numero = 0;}
	
	public CartaNumero(Colore colore, int numero) {
		super(colore);
		this.numero=numero;
	}
	
	@Override
	public void applicaEffetto(Partita p) {
		
	}
	
	@Override
	public boolean giocabileSu(Carta c) {
		if(this.colore==c.colore || this.colore==Colore.NERO)
			return true;
		if(c instanceof CartaNumero && ((CartaNumero)c).numero==this.numero)
			return true;
		return false;
	}
	
	public int getNumero() {
		return numero;
	}
	
	public void setNumero(int n) {
		this.numero=n;
	}
	@Override
	public String toString() {
		return "CartaNumero [numero=" + numero + ", colore=" + colore + "]";
	}

	@Override
	public int compareTo(Carta other) {
		switch(super.compareTo(other)) {
		case -1:{
			return -1;
		}
		case 0:{
			if(other instanceof CartaSpeciale)
				return 1;
			if(this.numero<((CartaNumero)other).numero)
				return -1;
			if(this.numero==((CartaNumero)other).numero)
				return 0;
			else
				return 1;
		}
		default:{
			return 1;
		}
		}
	}
	
}
