// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

import java.util.ArrayList;

import com.fasterxml.jackson.annotation.JsonIgnore;

import modello.Mossa.TipoMossa;
import modello.carte.*;
import modello.carte.CartaSpeciale.TipoSpeciale;
import modello.giocatori.Giocatore;

/************************************************************/

/**
 * classe centrale dove avviene il gioco
 * 
 * attributi importanti: 
 * lista dei giocatori riferimento al mazzo e alla pilascarti 
 * riferimento ad un navigatore--> gestione semplice della ciclazione dei giocatori 
 * riferimento alla carta corrente sul banco 
 * campi booleani per indicare direzione (true=orario) e se l'effetto della carta corrente è stato attivato (utile per salvataggio)
 * 
 * metodi importanti: 
 * eseguiPrePartita--> fornisce N carte a ciascun giocatore dal mazzo, mette giù la prima carta sul banco 
 * eseguiUnTurno--> esegue un ciclo di gioco (la turnazione adesso viene gestita dal controllore) 
 * vediProssimoGiocatore()--> restituisce prossimo giocatore dopo quello corrente, senza tuttavia cambiarlo (giro orario o antiorario gestito) 
 * prossimoGiocatore()--> come vediProssimoGiocatore, ma viene cambiato il giocatore corrente con il prossimo 
 * applicaEffettoCarta()--> prende la carta corrente e vi applica l'effetto --> effettoAttivato va messo a true 
 * applicaMossa()--> gestisce l'input del giocatore e prova ad applicare la sua mossa alla partita (mossa può essere rimandata al controllore in alcuni casi)
 * verificaFinePartita()-->invocato alla fine di ogni giocata da parte di un giocatore e controlla se non ha più carte (=vince) 
 * pescaCarta()-->fornisce INTERFACCIA per giocatore (pescare carta da mazzo e metterla nella sua mano) 
 * testaGiocaCarta()--> fornisce INTERFACCIA per giocatore (controllare se la carta che sta per giocare il giocatore è valida)
 * giocaCarta()--> fornisce INTERFACCIA per giocatore (mettere carta sul banco--> controlli fatti in giocatore, per ora)
 * 
 */
public class Partita implements PartitaIF {
	private ArrayList<Giocatore> giocatori;
	private Mazzo mazzo;
	private PilaScarti pilaScarti;
	private Navigatore<Giocatore> navigatore;
	private Carta cartaCorrente;
	private boolean direzione;
	private boolean effettoAttivato;
	@JsonIgnore
	private Giocatore vincitore;

	//costruttore vuoto per Jackson
	public Partita() {}
	
	public Partita(ArrayList<Giocatore> giocatori) {
		this.giocatori = giocatori;
		this.mazzo = new Mazzo();
		this.mazzo.inizializzaNuovoMazzo();
		this.pilaScarti = new PilaScarti();
		this.navigatore = new Navigatore<>(giocatori);
		this.cartaCorrente = null;
		this.direzione = true;
		this.effettoAttivato = true;
		mazzo.setPila(pilaScarti);
	}

	public void eseguiPrePartita() {
		for (Giocatore g : giocatori) {
			g.getMano().aggiungiCarta(mazzo.pescaN(7));
			//g.getMano().aggiungiCarta(new CartaSpeciale(Colore.NERO,TipoSpeciale.PIU_QUATTRO));
			//g.getMano().aggiungiCarta(new CartaSpeciale(Colore.NERO,TipoSpeciale.PIU_QUATTRO));
			//g.getMano().aggiungiCarta(new CartaSpeciale(Colore.GIALLO,TipoSpeciale.PIU_DUE));
			//g.getMano().aggiungiCarta(new CartaSpeciale(Colore.GIALLO,TipoSpeciale.PIU_DUE));
			//g.getMano().aggiungiCarta(new CartaNumero(Colore.BLU,2));
			//g.getMano().aggiungiCarta(new CartaNumero(Colore.GIALLO,4));
		}
		Carta first = mazzo.pesca();
		if (first.getColore() == Colore.NERO) {
			first.setColore(Colore.scegliColoreCasuale());
		}
		setCartaCorrente(first);
		//setCartaCorrente(new CartaNumero(Colore.ROSSO,0));
	}

	public void eseguiUnTurno() {
		if (verificaFinePartita()) 
			return;
		if (!effettoAttivato) {
			applicaEffettoCarta(cartaCorrente);
			effettoAttivato = true;
		}
		prossimoGiocatore();
	}

	public Carta getCartaCorrente() {
		return cartaCorrente;
	}

	private void setCartaCorrente(Carta cartaCorrente) {
		this.cartaCorrente = cartaCorrente;
	}
	
	public Mazzo getMazzo() {
		return this.mazzo;
	}
	
	public void cambiaDirezione() {
		direzione=!direzione;
	}
	
	@JsonIgnore
	public Giocatore getGiocatoreCorrente() {
		return navigatore.corrente();
	}

	public Giocatore vediProssimoGiocatore() {
		//direzione=true--> orario, direzione=false--> antiorario
		return direzione ? navigatore.vediProssimo() : navigatore.vediPrecedente();
	}

	public void prossimoGiocatore() {
		navigatore.setCorrente(vediProssimoGiocatore());
	}

	private void applicaEffettoCarta(Carta c) {
		c.applicaEffetto(this);
	}
	
	@JsonIgnore
	public Giocatore getVincitore() {
		return this.vincitore;
	}
	
	
	public Mossa applicaMossa(Giocatore g, Mossa mossa) {
		//caso 1:devo pescare
		if (mossa.getTipoMossa() == TipoMossa.PESCA) 
		{
	        Carta pescata = pescaCarta();
	        g.aggiungiCarta(pescata);
	        //verifico se posso giocare carta pescata--> Mossa modificata in GIOCA_CARTA
	        if (tentaGiocaCarta(pescata)) 
	        {
	        	mossa.setCartaScelta(pescata);
	        	mossa.setTipoMossa(TipoMossa.GIOCA_CARTA);
	            return mossa;
	        }
	        //altrimenti restituisco null--> Mossa CONCLUSA
	        else 
	        {
	            return null;
	        }
	    } 
		//caso 2:devo giocare carta 
		else if (mossa.getTipoMossa() == TipoMossa.GIOCA_CARTA 
				|| mossa.getTipoMossa()==TipoMossa.SCEGLI_COLORE) 
		{
			//verifico se posso giocare carta
	        if(tentaGiocaCarta(mossa.getCartaScelta())||(mossa.getTipoMossa()==TipoMossa.SCEGLI_COLORE)) 
	        {
	        	//verifico se la carta che gioco è NERA--> da cambiare il colore
	        	if(mossa.getCartaScelta().getColore()==Colore.NERO) {
	        		return mossa;
	        	}
	        	//la carta non è (più) da cambiare di colore--> Mossa CONCLUSA
	        	else 
	        	{
	        		g.rimuoveCarta(mossa.getCartaScelta());
					giocaCarta(mossa.getCartaScelta());
	        		return mossa;
	        	}
	        }
	        //altrimenti restituisco null--> carta NON giocabile
	        else 
	        	return null;
	    }
		//caso 3:nessun tipo specificato nella Mossa--
		else
			return null;
	}
	

	public boolean verificaFinePartita() {
		for (Giocatore g : giocatori) {
			if (g.getMano().getNumCarte() == 0) {
				vincitore=g;
				return true;
			}
		}
		return false;
	}

	@Override
	public Carta pescaCarta() {
		return mazzo.pesca();
		//return new CartaSpeciale(Colore.NERO,TipoSpeciale.JOLLY);
	}

	@Override
	public boolean tentaGiocaCarta(Carta tentativo) {
		return tentativo.giocabileSu(cartaCorrente);
	}

	@Override
	public void giocaCarta(Carta c) {
		if (cartaCorrente != null && cartaCorrente != c) { 
			if(cartaCorrente instanceof CartaSpeciale && (((CartaSpeciale)cartaCorrente).getTipo()==TipoSpeciale.JOLLY
						||((CartaSpeciale)cartaCorrente).getTipo()==TipoSpeciale.PIU_QUATTRO))
					cartaCorrente.setColore(Colore.NERO);
			
	        pilaScarti.mettiCarta(cartaCorrente);
	    }
		setCartaCorrente(c);
		effettoAttivato = false;
	}

	public ArrayList<Giocatore> getGiocatori() {
		return giocatori;
	}

	public void setGiocatori(ArrayList<Giocatore> giocatori) {
		this.giocatori = giocatori;
	}

	public PilaScarti getPilaScarti() {
		return pilaScarti;
	}

	public void setPilaScarti(PilaScarti pilaScarti) {
		this.pilaScarti = pilaScarti;
	}

	public Navigatore<Giocatore> getNavigatore() {
		return navigatore;
	}

	public void setNavigatore(Navigatore<Giocatore> navigatore) {
		this.navigatore = navigatore;
	}

	public boolean isDirezione() {
		return direzione;
	}

	public void setDirezione(boolean direzione) {
		this.direzione = direzione;
	}

	public boolean isEffettoAttivato() {
		return effettoAttivato;
	}

	public void setEffettoAttivato(boolean effettoAttivato) {
		this.effettoAttivato = effettoAttivato;
	}

	public void setMazzo(Mazzo mazzo) {
		this.mazzo = mazzo;
	}
	
	
}
