// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

/************************************************************/
/**
 * 
 */
abstract class Carta {
	/**
	 * 
	 */
	protected Colore colore;

	/**
	 * 
	 */
	public void getColore() {
	}

	/**
	 * 
	 */
	public abstract void giocabileSu();
}
