// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

/************************************************************/
/**
 * 
 */
public class CartaSpeciale extends Carta {
	/**
	 * 
	 */
	private TipoSpeciale tipo;

	/**
	 * 
	 */
	public void giocabileSu() {
	}

	/**
	 * 
	 */
	public void applicaEffetto() {
	}
}
