// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

/************************************************************/
/**
 * 
 */
public class CartaNumero extends Carta {
	/**
	 * 
	 */
	private int numero;

	/**
	 * 
	 */
	public void giocabileSu() {
	}
}
