// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

/************************************************************/
/**
 * 
 */
abstract class Giocatore {
	/**
	 * 
	 */
	protected String nome;
	/**
	 * 
	 */
	protected Mano mano;
	/**
	 * 
	 */
	protected boolean haPremutoOne;

	/**
	 * 
	 */
	public abstract void giocaTurno();

	/**
	 * 
	 */
	public void pescaCarta() {
	}

	/**
	 * 
	 */
	public void rimuoveCarta() {
	}

	/**
	 * 
	 */
	public void getNome() {
	}

	/**
	 * 
	 */
	public void getMano() {
	}

	/**
	 * 
	 */
	public void haPremutoOne() {
	}

	/**
	 * 
	 */
	public void setPremutoOne() {
	}
}
