// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

/************************************************************/
/**
 * 
 */
public class Mano {
	/**
	 * 
	 */
	private Carta[] carte;

	/**
	 * 
	 */
	public void aggiungiCarta() {
	}

	/**
	 * 
	 */
	public void rimuoviCarta() {
	}

	/**
	 * 
	 */
	public void getCarte() {
	}

	/**
	 * 
	 */
	public void getNumCarte() {
	}
}
