// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

/************************************************************/
/**
 * 
 */
public class Mazzo {
	/**
	 * 
	 */
	private Carta[] carte;

	/**
	 * 
	 */
	public void mescola() {
	}

	/**
	 * 
	 */
	public void pesca() {
	}

	/**
	 * 
	 */
	public void isVuoto() {
	}
}
