// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

/************************************************************/
/**
 * 
 */
public class PartitaIncompleta {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public Utente utente;
	/**
	 * 
	 */
	public String dettagliJSON;

	/**
	 * 
	 */
	public void toPartita() {
	}

	/**
	 * 
	 */
	public static void fromPartita() {
	}
}
