// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

import modello.giocatori.Giocatore;

/************************************************************/
/**
 * 
 */
public class Partita {
	/**
	 * 
	 */
	private Giocatore[] giocatori;
	/**
	 * 
	 */
	private Mazzo mazzo;
	/**
	 * 
	 */
	private PilaScarti pilaScarti;
	/**
	 * 
	 */
	private int turnoCorrente;
	/**
	 * 
	 */
	private boolean direzione;

	/**
	 * 
	 */
	public void avvia() {
	}

	/**
	 * 
	 */
	public void prossimoTurno() {
	}

	/**
	 * 
	 */
	public void getGiocatoreCorrente() {
	}

	/**
	 * 
	 */
	public void applicaEffettoCarta() {
	}

	/**
	 * 
	 */
	public void verificaFinePartita() {
	}

	/**
	 * 
	 */
	public void terminaPartita() {
	}
}
