// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello;

import modello.carte.Carta;

/************************************************************/
/**
 * 
 */
public class PilaScarti {
	/**
	 * 
	 */
	private Carta[] scarti;

	/**
	 * 
	 */
	public void ottieniCima() {
	}

	/**
	 * 
	 */
	public void mettiCarta() {
	}
}
