// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package onegame.modello.carte;

import java.util.Random;

/************************************************************/

/**
 * Enumerazione dei colori delle carte
 * 
 * valori possibili: ROSSO, BLU, GIALLO, VERDE, NERO
 * 
 *
 */
public enum Colore {
	ROSSO, BLU, GIALLO, VERDE, NERO;

	/**
	 * Metodo che genera un colore casuale (ROSSO, BLU, GIALLO, VERDE)
	 * 
	 * @return Colore casuale
	 */
	public static Colore scegliColoreCasuale() {
		Random r = new Random();
		return Colore.values()[r.nextInt(4)];
	}
}
