// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;

/************************************************************/
/**
 * 
 */
public class Bot extends Giocatore {
	/**
	 * 
	 */
	public void giocaTurno() {
	}

	/**
	 * 
	 */
	private void scegliMossa() {
	}
}
