// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;

import java.util.Scanner;

import modello.PartitaIF;
import modello.carte.Carta;

/************************************************************/

/**
 * classe che modella il giocatore in una partita
 * 
 * attributi importanti:
 * nome
 * booleano haPremutoOne per indicare se il giocatore ha una sola carta in mano
 * riferimento ad una mano--> contiente le carte del giocatore
 * riferimento ad una partita mediante un'interfaccia (settata)
 * 
 * metodi importanti:
 * giocaTurno()--> astratto, aspetto decisionale della partita (cambia tra bot e giocatore fisico)
 * pescaCarta()--> richiama il pescaCarta dalla partita
 * giocaCarta()--> richiama il giocaCarta dalla partita
 * 
 * 
 */
public abstract class Giocatore {
	protected String nome;
	protected boolean haPremutoOne;
	protected Mano mano;
	protected PartitaIF partitaIF;

	public Giocatore (String nome) {
		this.nome=nome;
		this.mano=new Mano();
		this.haPremutoOne=false;
		this.partitaIF=null;
	}
	
	public PartitaIF getInterfacciaPartita() {
		return partitaIF;
	}

	public void setInterfacciaPartita(PartitaIF interfacciaPartita) {
		this.partitaIF = interfacciaPartita;
	}
	
	public abstract void giocaTurno(Carta cartaCorrente, Scanner sc);

	/**
	 * 
	 */
	public void pescaCarta() {
		mano.aggiungiCarta(partitaIF.pescaCarta());
	}

	/**
	 * 
	 */
	public void rimuoveCarta(Carta c) {
		mano.rimuoviCarta(c);
		partitaIF.giocaCarta(c);
	}

	/**
	 * 
	 */
	public String getNome() {
		return this.nome;
	}

	/**
	 * 
	 */
	public Mano getMano() {
		return this.mano;
	}

	/**
	 * 
	 */
	public void haPremutoOne() {
	}

	/**
	 * 
	 */
	public void setPremutoOne() {
	}

	@Override
	public String toString() {
		return "Giocatore [nome=" + nome + ", carte=" + mano.getNumCarte() + "]";
	}
	
	protected String mostraCarteInMano() {
		String str="";
		int i=0;
		for(Carta c:mano.getCarte()) {
			str+=i+":"+c+"\n";
			i++;
		}
		return str;
	}
}
