// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;

import modello.PartitaIF;
import modello.carte.Carta;
import modello.giocatori.modalita.*;
import vista.TemporaryView;

/************************************************************/

/**
 * classe che modella il giocatore in una partita
 * 
 * attributi importanti:
 * nome
 * booleano haPremutoOne per indicare se il giocatore ha una sola carta in mano
 * riferimento ad una mano--> contiente le carte del giocatore
 * riferimento ad una partita mediante un'interfaccia (settata)
 * 
 * metodi importanti:
 * giocaTurno()--> astratto, aspetto decisionale della partita (cambia tra bot e giocatore fisico)
 * aggiungiCarta()--> aggiunge carta in mano
 * rimuoviCarta()--> rimuove carta dalla mano
 * cambiaModalita()--> cambia tra modalita bot e non-bot
 * 
 * 
 */
public abstract class Giocatore {
	protected String nome;
	protected boolean haPremutoOne;
	protected Mano mano;
	protected Modalita modalita;
	protected PartitaIF partitaIF;

	public Giocatore (String nome) {
		this.nome=nome;
		this.mano=new Mano();
		this.haPremutoOne=false;
		this.partitaIF=null;
		this.modalita=new NonBot();
	}
	
	public void aggiungiCarta(Carta c) {
		mano.aggiungiCarta(c);
	}
	
	public void rimuoveCarta(Carta c) {
		mano.rimuoviCarta(c);
	}
	
	public String getNome() {
		return this.nome;
	}
	
	public Mano getMano() {
		return this.mano;
	}
	
	public void haPremutoOne() {
	}
	
	public void setPremutoOne() {
	}
	
	public PartitaIF getInterfacciaPartita() {
		return partitaIF;
	}

	public void setInterfacciaPartita(PartitaIF interfacciaPartita) {
		this.partitaIF = interfacciaPartita;
	}
	
	public abstract void giocaTurno(String cartaCorrente, TemporaryView tv);

	public void cambiaModalita() {
		if(modalita instanceof Bot)
			modalita=new NonBot();
		else
			modalita=new Bot();
	}
	
	public String mostraCarteInMano() {
		String str="";
		int i=0;
		for(Carta c:mano.getCarte()) {
			str+=i+":"+c+"\n";
			i++;
		}
		return str;
	}
	
	@Override
	public String toString() {
		return "Giocatore [nome=" + nome + ", carte=" + mano.getNumCarte() + "]";
	}
	
}
