// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;

import java.util.Scanner;

import modello.carte.Carta;
import modello.tabelle.Utente;

/************************************************************/
/**
 * 
 */
public class GiocatoreRegistrato extends Giocatore {
	public GiocatoreRegistrato(String nome) {
		super(nome);
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 */
	private Utente utente;

	/**
	 * 
	 */
	public void getUtente() {
	}

	/**
	 * 
	 */
	public void aggiornaStatistiche() {
	}

	@Override
	public void giocaTurno(Carta cartaCorrente, Scanner sc) {
		// TODO Auto-generated method stub
		
	}
}
