// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;


/************************************************************/

/**
 * classe che modella il giocatore non loggato (potenzialmente anche il bot)
 * 
 */

public class GiocatoreAnonimo extends Giocatore {
	public GiocatoreAnonimo(String nome) {
		super(nome);
	}

}
