// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;

import modello.tabelle.Utente;
import vista.TemporaryView;

/************************************************************/
/**
 * 
 */
public class GiocatoreRegistrato extends Giocatore {
	public GiocatoreRegistrato(String nome) {
		super(nome);
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 */
	private Utente utente;

	/**
	 * 
	 */
	public void getUtente() {
	}

	/**
	 * 
	 */
	public void aggiornaStatistiche() {
	}


	@Override
	public void giocaTurno(String cartaCorrente, TemporaryView tv) {
		modalita.scegliMossa(cartaCorrente, tv, this);
	}
}
