// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;

import modello.tabelle.Utente;

/************************************************************/
/**
 * 
 */
public class GiocatoreRegistrato extends Giocatore {
	/**
	 * 
	 */
	private Utente utente;

	/**
	 * 
	 */
	public void getUtente() {
	}

	/**
	 * 
	 */
	public void aggiornaStatistiche() {
	}

	@Override
	public void giocaTurno() {
		// TODO Auto-generated method stub
		
	}
}
