// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;

import java.util.ArrayList;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonIgnore;

import modello.carte.Carta;

/************************************************************/

/**
 * classe che modella la mano di un giocatore
 * 
 * attributi importanti:
 * lista delle carte in mano
 * 
 * metodi importanti:
 * aggiungiCarta()--> aggiunge una carta o una lista di carte alla mano (overloading)
 * rimuoviCarta()--> rimuovi una carta dalla mano
 * 
 */
public class Mano {
	private ArrayList<Carta> carte;

	public Mano() {
		this.carte=new ArrayList<>();
	}
	public void aggiungiCarta(Carta c) {
		carte.add(c);
		Collections.sort(carte);
	}
	
	public void aggiungiCarta(ArrayList<Carta> c) {
		carte.addAll(c);
		Collections.sort(carte);
	}

	public void rimuoviCarta(Carta c) {
		carte.remove(c);
	}

	public ArrayList<Carta> getCarte() {
		return carte;
	}

	public void setCarte(ArrayList<Carta> carte) {
		this.carte = carte;
	}
	@JsonIgnore
	public int getNumCarte() {
		return carte.size();
	}
}
