// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.giocatori;

import java.util.ArrayList;

import modello.carte.Carta;

/************************************************************/
/**
 * 
 */
public class Mano {
	private ArrayList<Carta> carte;

	public Mano() {
		this.carte=new ArrayList<>();
	}
	public void aggiungiCarta(Carta c) {
		carte.add(c);
	}
	
	public void aggiungiCarta(ArrayList<Carta> c) {
		carte.addAll(c);
	}

	public void rimuoviCarta(Carta c) {
		carte.remove(c);
	}

	public ArrayList<Carta> getCarte() {
		return carte;
	}

	public int getNumCarte() {
		return carte.size();
	}
}
