// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.carte;

/************************************************************/
/**
 * 
 */
public class CartaSpeciale extends Carta {
	private final TipoSpeciale tipo;
	
	public CartaSpeciale(Colore colore, TipoSpeciale tipo) {
		super(colore);
		this.tipo=tipo;
	}
	/**
	 * 
	 */
	public boolean giocabileSu(Carta c) {
		if(this.colore==c.colore || this.colore==Colore.NERO|| this.tipo==((CartaSpeciale)c).tipo)
			return true;
		return false;
	}

	/**
	 * 
	 */
	public void applicaEffetto() {
	}
	
	public TipoSpeciale getTipo() {
		return tipo;
	}
	
	@Override
	public String toString() {
		return "CartaSpeciale [tipo=" + tipo + ", colore=" + colore + "]";
	}
	
}
