// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.carte;

/************************************************************/
/**
 * 
 */
public abstract class Carta {
	protected Colore colore;

	public Carta(Colore colore) {
		this.colore=colore;
	}
	
	public Colore getColore() {
		return this.colore;
	}
	

	public void setColore(Colore colore) {
		this.colore = colore;
	}

	/**
	 * 
	 */
	public abstract boolean giocabileSu(Carta c);
	
}
