// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.carte;

import modello.Partita;

/************************************************************/

/**
 * classe astratta che modella una carta generica
 * 
 * attributi importanti:
 * colore, che può essere cambiato (caso jolly)
 * 
 * metodi importanti:
 * giocabileSu()--> astratto, confronta la carta giocata(this) con quella sul banco (passato come input)
 * 
 */
public abstract class Carta {
	protected Colore colore;

	public Carta(Colore colore) {
		this.colore=colore;
	}
	
	public Colore getColore() {
		return this.colore;
	}
	

	public void setColore(Colore colore) {
		this.colore = colore;
	}
	
	public abstract void applicaEffetto(Partita p);

	/**
	 * 
	 */
	public abstract boolean giocabileSu(Carta c);
	
}
