// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.carte;

/************************************************************/
/**
 * 
 */
public enum TipoSpeciale {
	/**
	 * 
	 */
	piùDue,
	/**
	 * 
	 */
	piùQuattro,
	/**
	 * 
	 */
	blocca,
	/**
	 * 
	 */
	inverti,
	/**
	 * 
	 */
	colore
	;
}
