// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modello.carte;

/************************************************************/
/**
 * 
 */
public enum TipoSpeciale {
	/**
	 * 
	 */
	PIU_DUE,
	/**
	 * 
	 */
	PIU_QUATTRO,
	/**
	 * 
	 */
	BLOCCA,
	/**
	 * 
	 */
	INVERTI,
	/**
	 * 
	 */
	JOLLY
	;
}
